<?php

class Oddbrew_MailViewer_Block_Adminhtml_System_Email_Template_Grid_Renderer_Action_CreditmemoGuest extends Oddbrew_MailViewer_Block_Adminhtml_System_Email_Template_Grid_Renderer_Action_Abstract
{
    protected $_mailType = 'creditmemo_guest';
}