<?php

class Oddbrew_MailViewer_Block_Adminhtml_System_Email_Template_Grid_Renderer_Action_ShipmentGuest extends Oddbrew_MailViewer_Block_Adminhtml_System_Email_Template_Grid_Renderer_Action_Abstract
{
    protected $_mailType = 'shipment_guest';
}